Update ovz7transfer

diff --git a/ovz7transfer b/ovz7transfer
--- a/ovz7transfer
+++ b/ovz7transfer
@@ -60,37 +60,37 @@ CTID_LIST=$(vzlist -a | awk '{print $1}' | grep -v CTID)
 screen -dmS vm_management
 
 # Run the VM management script inside the screen session
-screen -S vm_management -X stuff "
+screen -S vm_management -X stuff '
 for CTID in $CTID_LIST; do
-    echo 'Managing VM $CTID'
-    
+    echo "Managing VM $CTID"
+
     vzctl stop $CTID >> ovztransfer.log 2>&1
-    
-    CONFIG_FILE=\"/etc/sysconfig/vz-scripts/$CTID.conf\"
-    if [ -f \$CONFIG_FILE ]; then
-        if grep -q 'DISABLED=\"yes\"' \$CONFIG_FILE; then
-            sed -i 's/DISABLED=\"yes\"/DISABLED=\"no\"/' \$CONFIG_FILE
-            echo 'VM $CTID has been enabled.' >> ovztransfer.log 2>&1
+
+    CONFIG_FILE="/etc/sysconfig/vz-scripts/$CTID.conf"
+    if [ -f $CONFIG_FILE ]; then
+        if grep -q 'DISABLED="yes"' $CONFIG_FILE; then
+            sed -i 's/DISABLED="yes"/DISABLED="no"/' $CONFIG_FILE
+            echo "VM $CTID has been enabled." >> ovztransfer.log 2>&1
         else
-            echo 'VM $CTID is already enabled.' >> ovztransfer.log 2>&1
+            echo "VM $CTID is already enabled." >> ovztransfer.log 2>&1
         fi
     else
-        echo 'Configuration file \$CONFIG_FILE not found.' >> ovztransfer.log 2>&1
+        echo "Configuration file $CONFIG_FILE not found." >> ovztransfer.log 2>&1
     fi
 
-    ./ovztransfer.sh \$REMOTE_IP \$CTID:\$CTID >> ovztransfer.log 2>&1
+    ./ovztransfer.sh $REMOTE_IP $CTID:$CTID >> ovztransfer.log 2>&1
 
-    if [ \$? -eq 0 ]; then
-        echo 'Transfer for VM $CTID was successful.'
+    if [ $? -eq 0 ]; then
+        echo "Transfer for VM $CTID was successful."
     else
-        echo 'Transfer for VM $CTID failed. Skipping VM.' >> ovztransfer.log 2>&1
+        echo "Transfer for VM $CTID failed. Skipping VM." >> ovztransfer.log 2>&1
         continue
     fi
 
     vzctl start $CTID >> ovztransfer.log 2>&1
 
-    echo 'VM $CTID management completed.' >> ovztransfer.log
+    echo "VM $CTID management completed." >> ovztransfer.log
 done
-"
+'
 
 echo "VM management script is running in a detached screen session."
